name: Deploy on GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        working-directory: frontend
        run: yarn install
      - name: Build
        working-directory: frontend
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          yarn build
          cp ./CNAME ./public
        shell: bash
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public
          clean: false
